"""
US States, Florida Cities, and ZIP Code Data
For Chicken Kitchen HR Forms App
"""

US_STATES = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
]

FL_CITIES = [
    "Aventura", "Boca Raton", "Boynton Beach", "Clearwater", "Coconut Creek",
    "Coconut Grove", "Cooper City", "Coral Gables", "Coral Springs", "Cutler Bay",
    "Davie", "Deerfield Beach", "Delray Beach", "Doral", "Fort Lauderdale",
    "Fort Myers", "Gainesville", "Hallandale Beach", "Hialeah", "Hialeah Gardens",
    "Hollywood", "Homestead", "Jacksonville", "Kendall", "Key Biscayne",
    "Kissimmee", "Lake Worth", "Margate", "Miami", "Miami Beach",
    "Miami Gardens", "Miami Lakes", "Miami Springs", "Miramar", "Naples",
    "North Bay Village", "North Miami", "North Miami Beach", "Oakland Park", "Opa-locka",
    "Orlando", "Palmetto Bay", "Pembroke Pines", "Pinecrest", "Plantation",
    "Pompano Beach", "St. Petersburg", "Sunny Isles Beach", "Sunrise", "Sweetwater",
    "Tallahassee", "Tamarac", "Tampa", "West Miami", "West Palm Beach",
    "Weston", "Wilton Manors",
]

US_BANKS = [
    "Ally Bank",
    "American Express National Bank",
    "Ameris Bank",
    "Atlantic Capital Bank",
    "Axiom Bank",
    "BAC Florida Bank",
    "BancorpSouth Bank",
    "Bank of America",
    "Bank of the Ozarks",
    "BB&T (now Truist)",
    "BBVA USA",
    "BMO Harris Bank",
    "BankUnited",
    "Capital One",
    "Centennial Bank",
    "CenterState Bank",
    "Chase (JPMorgan Chase)",
    "CIT Bank",
    "Citibank",
    "Citizens Bank",
    "City National Bank of Florida",
    "Coastal Community Bank",
    "Columbia Bank",
    "Comerica Bank",
    "Community Bank of the Chesapeake",
    "Customers Bank",
    "Dime Community Bank",
    "Discover Bank",
    "EverBank (now TIAA Bank)",
    "Fidelity Bank",
    "Fifth Third Bank",
    "First Citizens Bank",
    "First Federal Savings",
    "First Horizon Bank",
    "First National Bank",
    "FirstBank",
    "Flagler Bank",
    "Florida Capital Bank",
    "Gateway Bank of Central Florida",
    "Globe Bank",
    "Goldman Sachs Bank (Marcus)",
    "Great Southern Bank",
    "Green Dot Bank",
    "Gulf Coast Bank & Trust",
    "Hancock Whitney Bank",
    "Home BancFidelity",
    "HSBC Bank USA",
    "Huntington National Bank",
    "IberiaBank (now First Horizon)",
    "Independent Bank",
    "International Finance Bank",
    "KeyBank",
    "Lending Club Bank",
    "Live Oak Bank",
    "M&T Bank",
    "Mercantil Commercebank",
    "Metropolitan National Bank",
    "Morgan Stanley Private Bank",
    "Navy Federal Credit Union",
    "New York Community Bank",
    "Northern Trust",
    "Ocean Bank",
    "Old National Bank",
    "Pacific Premier Bank",
    "PNC Bank",
    "Popular Bank",
    "Professional Bank",
    "Regions Bank",
    "Republic Bank",
    "Sabadell United Bank",
    "Santander Bank",
    "Seacoast Banking Corp",
    "Signature Bank",
    "Silicon Valley Bank",
    "South State Bank",
    "Southeast Mortgage",
    "Stonegate Bank",
    "SunTrust (now Truist)",
    "Synovus Bank",
    "TD Bank",
    "TotalBank",
    "Truist Financial",
    "U.S. Bank",
    "UBS Bank USA",
    "Umpqua Bank",
    "United Community Bank",
    "Valley National Bank",
    "Voya Financial",
    "Washington Federal",
    "Webster Bank",
    "Wells Fargo",
    "Zions Bancorporation",
]

FL_ZIPS = {
    "Aventura": "33180", "Boca Raton": "33431", "Boynton Beach": "33426",
    "Clearwater": "33755", "Coconut Creek": "33073", "Coconut Grove": "33133",
    "Cooper City": "33328", "Coral Gables": "33134", "Coral Springs": "33065",
    "Cutler Bay": "33157", "Davie": "33314", "Deerfield Beach": "33441",
    "Delray Beach": "33444", "Doral": "33172", "Fort Lauderdale": "33301",
    "Fort Myers": "33901", "Gainesville": "32601", "Hallandale Beach": "33009",
    "Hialeah": "33012", "Hialeah Gardens": "33018", "Hollywood": "33020",
    "Homestead": "33030", "Jacksonville": "32099", "Kendall": "33156",
    "Key Biscayne": "33149", "Kissimmee": "34741", "Lake Worth": "33460",
    "Margate": "33063", "Miami": "33130", "Miami Beach": "33139",
    "Miami Gardens": "33056", "Miami Lakes": "33014", "Miami Springs": "33166",
    "Miramar": "33023", "Naples": "34102", "North Bay Village": "33141",
    "North Miami": "33161", "North Miami Beach": "33162", "Oakland Park": "33334",
    "Opa-locka": "33054", "Orlando": "32801", "Palmetto Bay": "33157",
    "Pembroke Pines": "33024", "Pinecrest": "33156", "Plantation": "33317",
    "Pompano Beach": "33060", "St. Petersburg": "33701", "Sunny Isles Beach": "33160",
    "Sunrise": "33322", "Sweetwater": "33174", "Tallahassee": "32301",
    "Tamarac": "33321", "Tampa": "33602", "West Miami": "33144",
    "West Palm Beach": "33401", "Weston": "33326", "Wilton Manors": "33305",
}
